### ISSUE TITLE
umi-mock例子无法运行

### ISSUE THREAD

**Issue by guwan** [remaxjs/examples#37]
运行yarn dev

报如下错误：
yarn run v1.22.5
error Couldn't find a package.json file in "F:\\IdeaProjects\\examples"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

F:\IdeaProjects\examples>cd umi-mock

F:\IdeaProjects\examples\umi-mock>yarn dev
yarn run v1.22.5
$ concurrently 'remax build -t ali -w' 'umi dev'
F:\IdeaProjects\examples\umi-mock\node_modules\rxjs\internal\util\hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

RangeError: Format string contains an unescaped latin alphabet character `l`
    at F:\IdeaProjects\examples\umi-mock\node_modules\date-fns\format\index.js:442:13
    at Array.map (<anonymous>)
    at format (F:\IdeaProjects\examples\umi-mock\node_modules\date-fns\format\index.js:415:45)
    at Logger.getPrefixesFor (F:\IdeaProjects\examples\umi-mock\node_modules\concurrently\src\logger.js:38:19)
    at Logger.getPrefix (F:\IdeaProjects\examples\umi-mock\node_modules\concurrently\src\logger.js:48:31)
    at Logger.logCommandText (F:\IdeaProjects\examples\umi-mock\node_modules\concurrently\src\logger.js:73:53)
    at SafeSubscriber._next (F:\IdeaProjects\examples\umi-mock\node_modules\concurrently\src\flow-control\log-output.js:9:58)
    at SafeSubscriber.__tryOrUnsub (F:\IdeaProjects\examples\umi-mock\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (F:\IdeaProjects\examples\umi-mock\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (F:\IdeaProjects\examples\umi-mock\node_modules\rxjs\internal\Subscriber.js:89:26)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by watsonhaw5566** [comment]
你好，经常我们这边测试是可以的，麻烦检查一下是否是依赖包安装的问题。建议使用国内npm源
